-- 코드를 입력하세요
# SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO RI
#     INNER JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
# WHERE RI.ADDRESS LIKE '%서울%'
# GROUP BY RI.REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC;


SELECT
    i.REST_ID,
    i.REST_NAME,
    i.FOOD_TYPE,
    i.FAVORITES,
    i.ADDRESS,
    ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM
    REST_INFO i INNER JOIN REST_REVIEW r
    ON i.REST_ID = r.REST_ID
WHERE
    i.ADDRESS LIKE '서울%'
GROUP BY
    i.REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC;