-- 코드를 입력하세요
SELECT AP.APNT_NO, PT.PT_NAME,  AP.PT_NO, AP.MCDP_CD, DC.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
    JOIN DOCTOR DC ON AP.MDDR_ID = DC.DR_ID
    JOIN PATIENT PT ON AP.PT_NO = PT.PT_NO
WHERE 
    AP.MCDP_CD = 'CS'
    AND YEAR(APNT_YMD) = 2022
    AND MONTH(APNT_YMD) = 4
    AND DAY(APNT_YMD) = 13
    AND AP.APNT_CNCL_YMD IS NULL
ORDER BY 6 ASC;


# SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
# FROM APPOINTMENT AS C
#     JOIN PATIENT AS A ON C.PT_NO = A.PT_NO
#     JOIN DOCTOR AS B ON C.MDDR_ID = B.DR_ID
# WHERE C.MCDP_CD = 'CS' 
#     AND YEAR(APNT_YMD) = 2022
#     AND MONTH(APNT_YMD) = 4 
#     AND DAY(APNT_YMD) = 13 
#     AND APNT_CNCL_YMD IS NULL
# ORDER BY APNT_YMD ASC