WITH RECURSIVE HOURS AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM HOURS WHERE H < 23
)

SELECT
    H AS HOUR,
    COALESCE(COUNT(A.DATETIME), 0) AS COUNT

FROM HOURS
    LEFT JOIN ANIMAL_OUTS A ON H = HOUR(A.DATETIME)

GROUP BY H

ORDER BY H;