-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    MONTH(START_DATE) BETWEEN 8 AND 10 AND
    CAR_ID IN ( SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE MONTH(START_DATE) BETWEEN 8 AND 10
                GROUP BY CAR_ID HAVING COUNT(CAR_ID) >= 5
              )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY 1 ASC, 2 DESC;






# SELECT MONTH(START_DATE) MONTH,CAR_ID,COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 
#     START_DATE>='2022-08-01' and START_DATE<'2022-11-01' and 
#     CAR_ID in (SELECT CAR_ID 
#                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#                 WHERE START_DATE>='2022-08-01' and START_DATE<'2022-11-01'
#                 GROUP BY CAR_ID 
#                 HAVING COUNT(CAR_ID)>=5
#               )
# GROUP BY CAR_ID,MONTH(START_DATE)
# ORDER BY MONTH,CAR_ID DESC